### ISSUE TITLE
A test in the DOM Editing Lab is misleading 

### ISSUE THREAD

**Issue by adamtwright7** [learn-co-curriculum/phase-0-the-dom-editing-lab#10]
### Canvas Link

https://learning.flatironschool.com/courses/6150/assignments/209285?module_item_id=482795

### Concern

"npm test" and "learn test" both show that my code has one failure remaining even after completing the lab. I checked my index.html with validator.w3.org until it showed no errors, and my document clearly contains an "h1" tag. I also trimmed training whitespace -- not sure why that would help, but it resolved an error in a previous lesson. 

![Screenshot (274)](https://user-images.githubusercontent.com/116467575/200141091-bb9ae255-a63f-414f-b8d5-2c026b395351.png)
![Screenshot (275)](https://user-images.githubusercontent.com/116467575/200141147-6897c941-7a8e-427e-bd0f-a48a33858de7.png)

After checking the code of the tests, I resolved the issue and got all of the tests to pass. To be clear, the issue was that line 10 of my index.html contained spaces between the tag and the content within. I still think this is a misleading test. 

### Additional Context

A call of "learn test" with all changes committed. 

![Screenshot (276)](https://user-images.githubusercontent.com/116467575/200141278-d541473e-dcb2-425a-9e3d-8546389c8aeb.png)

### Suggested Changes

Change the tests to search for an "h1" tag in index.html, or change the text shown to the student to be more clear about the preciseness of the test. 

Specifically, change lines 10-12 in indexTest.js from 

```
  it("contains an <h1> tag", () => {
    expect(document.querySelector('body').innerHTML).to.include('<h1>My HTML adventure</h1>')
  })
```

to 

 ```
 it("contains an <h1> tag", () => {
    expect(document.querySelector('body').innerHTML).to.include('<h1>')
  })
```

or 

 ```
 it("contains <h1>My HTML adventure</h1>", () => {
    expect(document.querySelector('body').innerHTML).to.include('<h1>My HTML adventure</h1>')
  })
```

**Comment by jlboba** [comment]
Hello, and thank you for spotting this issue and providing feedback.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not!
We appreciate your support! 💙
