### ISSUE TITLE
A vs An article error.

### ISSUE THREAD

**Issue by codified45** [learn-co-curriculum/phase-0-the-dom-editing-lab#13]
### Canvas Link

https://learning.flatironschool.com/courses/6150/assignments/209285?module_item_id=482795

### Concern

When running the `learn test` command for this module, the results read as follows:

> > javascript-lab@1.0.0 test
> > mocha --timeout 5000 -R mocha-multi --reporter-options spec=-,json=.results.json --bail
> 
> > within index.html
> >  ✓ contains a \<body> tag
> >  ✓ contains a \<body> tag
> >  ✓ contains an \<h1> tag
> >  ✓ contains a \<p> tag
> >  ✓ within the \<p>, it contains a \<strong> tag
> >  ✓ within the \<p>, it contains an \<em> tag
> >  ✓ within the \<p>, it contains an \<a> tag
> > ✓ within the \<body>, it contains an \<table> tag

For consistency, the end of the last line should read "a \<table> tag" since three lines above reads "a \<strong> tag". 

### Additional Context

[Articles: A versus An - Purdue OWL](https://owl.purdue.edu/owl/general_writing/grammar/articles_a_versus_an.html#:~:text=If%20the%20first%20letter%20makes,words%20that%20begin%20with%20consonants.)

**Comment by jlboba** [comment]
Hello, and thank you for spotting this issue and providing feedback.

We have updated the GitHub repo and believe your issue to have been resolved. 
We appreciate your support! 💙
